name: continuous integration

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  normal:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 25 ]
    name: Java ${{matrix.java}}    
    steps:
      - name: check out app
        uses: actions/checkout@v4.1.1
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25    
      - name: prepare
        run: |

      - name: install
        shell: bash
        run: mvn compile
